# Generated by Django 5.0.7 on 2024-07-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        help_text="Ведите имя пользователя",
                        max_length=150,
                        verbose_name="Имя пользователя",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Ведите номер телефона",
                        max_length=50,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "massage",
                    models.TextField(
                        blank=True,
                        help_text="Ведите сообщение",
                        null=True,
                        verbose_name="Сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "контакты",
                "verbose_name_plural": "контакты",
                "ordering": ["user_name"],
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(
                help_text="Ведите категорию продукта",
                max_length=150,
                verbose_name="Категория продукта",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Ведите описание категории",
                verbose_name="Описание категории",
            ),
        ),
    ]
